version: '3.8'

services:
  # Serviço para desenvolvimento
  app-dev:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app  # Sincroniza o código-fonte local com o container
      - /usr/src/app/node_modules # Evita conflitos com node_modules no host
    command: npm run dev

  # Serviço para produção
  app-prod:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: node dist/api.js
